version: 2
jobs:
  prepare:
    docker:
    - image: cypress/browsers:node10.2.1-chrome74
    steps:
    - checkout: {}
    - restore_cache:
        keys:
        - myapps-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install --save-dev && npm test
    - run: npm run start
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    
    - - persist_to_workspace:
          root: .
          paths:
            - node_modules    
  e2e_test:
    docker:
    - image: cypress/browsers:node10.2.1-chrome74
    steps:
    - checkout: {}
    - attach_workspace:
          at: .    
    - restore_cache:
        keys:
        - myapps2-{{ .Branch }}-{{ checksum "package.json" }}
    - run: npm install && npm run beta
    - save_cache:
        key: myapp-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/npm
        - ~/.cache
    - store_artifacts:
        path: /root/project/cypress/snapshots
        destination: visual-regression
    
workflows:
  version: 2
  build_and_test:
    jobs:
    - Prepare
         requires:
           - e2e_test