describe('e2e test for the quint', () => {
    beforeEach(() => {cy.viewport("macbook-15")})
it(`all metatags visible on storypages on `, () => { 
    cy.visit("https://thequint-beta-fit.quintype.io/health-news/remedies-to-protect-children-from-encephalitis-fact-check")
    // cy.get('div#container > div > div:nth-of-type(3) > div > section > div > div > div > div > div > article:nth-of-type(2) > a > h3').click({timeout:600000})
   
    cy.get('meta[name="description"]')
     .should("have.attr", "content")
    cy.get('meta[property= "og:title"]')    
     .should("have.attr", "content")
    cy.get('meta[property= "og:description"]')
     .should("have.attr", "content")
    cy.get('meta[property= "og:type"]')
     .should("have.attr", "content")
    cy.get('meta[property= "og:url"]')
     .should("have.attr", "content")
    cy.get('meta[property= "og:image:width"]')
     .should("have.attr", "content")
    cy.get('meta[name= "al:android:package"]')
     .should("have.attr", "content")
    cy.get('meta[name= "twitter:title"]')
     .should("have.attr", "content")
    cy.get('meta[name= "al:android:app_name"]')
     .should("have.attr", "content")
    cy.get('meta[name= "al:android:url"]')
     .should("have.attr", "content")
    cy.get('meta[name= "news_keywords"]')
     .should("have.attr", "content")
    cy.get('meta[name= "keywords"]')
     .should("have.attr", "content")
    cy.get('meta[name= "twitter:description"]')
     .should("have.attr", "content")
    cy.get('meta[name= "msvalidate.01"]')
     .should("have.attr", "content")
    cy.get('meta[property= "fb:app_id"]')
     .should("have.attr", "content")
    cy.get('meta[name="viewport"]')
     .should("have.attr", "content")
    cy.get('meta[name="mobile-web-app-capable"]')
    .should("have.attr", "content")
    cy.get('meta[name="format-detection"]')
    .should("have.attr", "content")
    cy.get('meta[name="HandheldFriendly"]')
    .should("have.attr", "content")
    cy.get('meta[name="csrf-param"]')
    .should("have.attr", "content")
    cy.get('meta[name="csrf-token"]')
    .should("have.attr", "content")
    cy.get('meta[property="og:site_name"]')
    .should("have.attr", "content")
    cy.get('meta[name="msvalidate.01"]')
    .should("have.attr", "content")
    cy.get('meta[name="al:android:app_name"]')

   
    })
    })
    
   
  
    